#!/usr/bin/env node
// Version B – Consolidate calculator functions into a single calculators.js
// Usage: node extract_calculators.js path/to/app.js

const fs = require('fs');
const path = require('path');

if (process.argv.length < 3) {
  console.error('Usage: node extract_calculators.js path/to/app.js');
  process.exit(1);
}

const infile = process.argv[2];
if (!fs.existsSync(infile)) {
  console.error(`File not found: ${infile}`);
  process.exit(1);
}

const code = fs.readFileSync(infile, 'utf8');

// --- Patterns for calculator-style functions ---
const patterns = [
  /MLAQuizApp\.prototype\.([A-Za-z0-9_]*calculate[A-Za-z0-9_]*)\s*=\s*function\s*\([^)]*\)\s*\{/g,
  /MLAQuizApp\.prototype\.([A-Za-z0-9_]*calculate[A-Za-z0-9_]*)\s*=\s*\([^)]*\)\s*=>\s*\{/g,
  /MLAQuizApp\.prototype\.([A-Za-z0-9_]*get[A-Za-z0-9_]*Calculator)\s*=\s*function\s*\([^)]*\)\s*\{/g,
  /(?:^|\n)\s*([A-Za-z0-9_]*calculate[A-Za-z0-9_]*)\s*\([^)]*\)\s*\{/g,
  /(?:^|\n)\s*([A-Za-z0-9_]*get[A-Za-z0-9_]*Calculator)\s*\([^)]*\)\s*\{/g
];

// --- Helper: extract balanced brace block ---
function extractBlockAt(startIndex) {
  let i = startIndex;
  if (code[i] !== '{') i = code.indexOf('{', i);
  if (i === -1) return null;
  let depth = 0, inString = null, escaped = false;
  for (let j = i; j < code.length; j++) {
    const ch = code[j];
    if (inString) {
      if (escaped) escaped = false;
      else if (ch === '\\') escaped = true;
      else if (ch === inString) inString = null;
    } else {
      if (ch === '"' || ch === "'" || ch === '`') inString = ch;
      else if (ch === '{') depth++;
      else if (ch === '}') {
        depth--;
        if (depth === 0) return code.slice(i, j + 1);
      }
    }
  }
  return null;
}

// --- Locate all matching functions ---
const found = [];
patterns.forEach(pat => {
  let m;
  while ((m = pat.exec(code)) !== null) {
    const name = m[1];
    if (found.some(f => f.name === name)) continue;
    const bracePos = code.indexOf('{', m.index + m[0].length - 1);
    if (bracePos === -1) continue;
    const body = extractBlockAt(bracePos);
    if (!body) continue;
    found.push({ name, start: m.index, header: code.slice(m.index, bracePos).split('\n').pop().trim(), body });
  }
});
found.sort((a, b) => a.start - b.start);

// --- Compose single calculators.js output ---
let output = `// Auto-generated by extract_calculators.js
// Consolidated calculator functions from ${path.basename(infile)}
// Timestamp: ${new Date().toISOString()}

`;

const exportsList = [];
for (const f of found) {
  const funcName = f.name.replace(/[^A-Za-z0-9_]/g, '_');
  output += `\n// ===== ${funcName} =====\nfunction ${funcName}${f.body}\n`;
  exportsList.push(funcName);
}

output += `\nmodule.exports = { ${exportsList.join(', ')} };\n`;

fs.writeFileSync('calculators.js', output, 'utf8');
fs.writeFileSync('calculators_index.json', JSON.stringify(found.map(f => f.name), null, 2), 'utf8');

console.log(`Extracted ${found.length} calculator function(s) into calculators.js`);
